import { useEffect, useState } from "react";
import { getPayments, getGateways } from "../services/api";

function RoutingDecisions() {
    const [payments, setPayments] = useState([]);
    const [gateways, setGateways] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadData();
    }, []);

    const loadData = async () => {
        try {
            const [paymentsData, gatewaysData] = await Promise.all([
                getPayments(),
                getGateways()
            ]);

            setPayments(paymentsData);
            setGateways(gatewaysData);
        } catch (error) {
            console.error("AI routing data load failed:", error);
        } finally {
            setLoading(false);
        }
    };

    const getGateway = (name) => {
        return gateways.find(
            (gateway) => gateway.name === name
        );
    };

    if (loading) {
        return (
            <div className="page-container">
                <h1>AI Routing Decisions</h1>
                <p>Loading AI decisions...</p>
            </div>
        );
    }

    return (
        <div className="page-container">

            <div className="page-header">
                <div>
                    <h1>AI Routing Decisions</h1>
                    <p>
                        Real-time payment decisions generated by GenAI
                    </p>
                </div>
            </div>

            <div className="routing-list">

                {payments.length === 0 ? (
                    <div className="empty-state">
                        No AI decisions available.
                    </div>
                ) : (
                    payments.map((payment) => {

                        const gateway =
                            getGateway(payment.final_gateway);

                        const isRecovered =
                            payment.status === "RECOVERED";

                        return (
                            <div
                                className="routing-card"
                                key={payment.id}
                            >

                                {/* Header */}
                                <div className="routing-card-header">

                                    <div>
                                        <h3>
                                            {payment.transaction_id}
                                        </h3>

                                        <span>
                                            {payment.created_at
                                                ? new Date(
                                                    payment.created_at
                                                ).toLocaleString()
                                                : ""}
                                        </span>
                                    </div>

                                    <div className="ai-badge">
                                        🤖 GenAI
                                    </div>

                                </div>

                                {/* Payment Flow */}
                                <div className="routing-flow">

                                    <div className="routing-step">
                                        <span>Payment</span>

                                        <strong>
                                            ₹{Number(
                                                payment.amount
                                            ).toLocaleString()}
                                        </strong>
                                    </div>

                                    <div className="routing-arrow">
                                        →
                                    </div>

                                    <div className="routing-step">
                                        <span>Initial Gateway</span>

                                        <strong>
                                            {payment.initial_gateway || "-"}
                                        </strong>
                                    </div>

                                    <div className="routing-arrow">
                                        →
                                    </div>

                                    <div className="routing-step">
                                        <span>Final Gateway</span>

                                        <strong>
                                            {payment.final_gateway || "-"}
                                        </strong>
                                    </div>

                                </div>

                                {/* AI Generated Analysis */}
                                <div className="ai-analysis-card">

                                    <div className="ai-analysis-header">
                                        <div>
                                            <span className="ai-analysis-icon">
                                                🤖
                                            </span>

                                            <strong>
                                                AI Analysis
                                            </strong>
                                        </div>

                                        <span className="ai-generated">
                                            Generated by Groq
                                        </span>
                                    </div>

                                    <p className="ai-reason">
                                        {payment.ai_reason ||
                                            "AI analysis is not available for this transaction."}
                                    </p>

                                    <div className="ai-analysis-stats">

                                        <div>
                                            <span>Confidence</span>

                                            <strong>
                                                {payment.ai_confidence !== null &&
                                                payment.ai_confidence !== undefined
                                                    ? `${payment.ai_confidence}%`
                                                    : "-"}
                                            </strong>
                                        </div>

                                        <div>
                                            <span>AI Action</span>

                                            <strong>
                                                {payment.ai_action || "-"}
                                            </strong>
                                        </div>

                                        <div>
                                            <span>Selected Gateway</span>

                                            <strong>
                                                {payment.final_gateway || "-"}
                                            </strong>
                                        </div>

                                    </div>

                                </div>

                                {/* Transaction Details */}
                                <div className="routing-details">

                                    <div>
                                        <span>Gateway Success Rate</span>

                                        <strong>
                                            {gateway
                                                ? `${gateway.success_rate}%`
                                                : "-"}
                                        </strong>
                                    </div>

                                    <div>
                                        <span>Latency</span>

                                        <strong>
                                            {payment.latency
                                                ? `${payment.latency} ms`
                                                : "-"}
                                        </strong>
                                    </div>

                                    <div>
                                        <span>Attempts</span>

                                        <strong>
                                            {payment.attempts || "-"}
                                        </strong>
                                    </div>

                                    <div>
                                        <span>Recovery</span>

                                        <strong>
                                            {isRecovered
                                                ? "Automatic Recovery"
                                                : "Not Required"}
                                        </strong>
                                    </div>

                                    <div>
                                        <span>Payment Method</span>

                                        <strong>
                                            {payment.payment_method || "-"}
                                        </strong>
                                    </div>

                                    <div>
                                        <span>Status</span>

                                        <strong>
                                            {payment.status || "-"}
                                        </strong>
                                    </div>

                                </div>

                            </div>
                        );
                    })
                )}

            </div>

        </div>
    );
}

export default RoutingDecisions;